version: '3'
services:

  database:
    image: "postgres"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - spring-cloud-network
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    build: .
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_LISTENERS: PLAINTEXT://:9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

  mytrip-backend:
    image: "domchowit/mytrip-backend"
    expose:
        - 8080
    ports:
        - 8080:8080
    depends_on:
        - database
    networks:
        - spring-cloud-network
        - client-server-network

  mytrip-client:
    image: "domchowit/mytrip-client"
    ports:
        - 80:80
    networks:
        - client-server-network

networks:
  spring-cloud-network:
    driver: bridge
  client-server-network:
    driver: bridge
volumes:
  database-data:
